spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema:

  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:person.sql
logging:
  level:
    org.springframework.batch: debug
